### ISSUE TITLE
Better slicing

### ISSUE THREAD

**Issue by masonwheeler** [Quansight-Labs/numpy.net#1]
In readme.md, you mention how C# lacks support for Python-style slicing, so everything's done with string parsing instead.

Have you seen [the new slicing support added in C# 8](https://www.codejourney.net/2019/02/csharp-8-slicing-indexes-ranges/)?  That introduces new types to handle the begin and end part of slicing, at least, while the third parameter could be easily made an int rather than a string.

Also, have you looked at `Span<T>` and `Memory<T>`?  As Numpy is supposed to be a high-performance computational library, having support for them would be very nice...

**Comment by KevinBaselinesw** [comment]
I have looked at that a little bit.  Unfortunately I don't think it is really compatible with the underlying numpy logic which is what my tool is replicating.   There are hundreds of functions that depend on the core logic of numpy slicing which probably would not work very well with this C# 8 method.

I believe the people who are working on this repository; https://github.com/SciSharp/NumSharp are using that mechanism.  I think they are having mixed success with it.
