### ISSUE TITLE
about slicing

### ISSUE THREAD

**Issue by goodtogood** [Quansight-Labs/numpy.net#13]
```
a = np.load('./sample.npy') # (10,10,3)
R = img[:, :, 0]
G = img[:, :, 1]
B = img[:, :, 2]
print(R.shape,G.shape,B.shape)
(10, 10) (10, 10) (10, 10)
```
```
imgnd # (10,10,3)
var r = (ndarray)imgnd[":", ":", "0"];
var g = (ndarray)imgnd[":", ":", "1"];
var b = (ndarray)imgnd[":", ":", "2"];
 Console.WriteLine($"{r.shape}   {g.shape}   {b.shape}");
(10, 10, 3)   (10, 10, 2)   (10, 10, 1)
```
Was I  wrong about slicing via C#?
thanks!

**Comment by KevinBaselinesw** [comment]
Try one of these forms instead.  I am interpreting the "0", as "new Slice(0)" instead of as an index which takes a different path.

           var r = (ndarray)imgnd[":", ":", 0];
            var g = (ndarray)imgnd[":", ":", 1];
            var b = (ndarray)imgnd[":", ":", 2];

            r = imgnd.A(":", ":", 0);
            g = imgnd.A(":", ":", 1);
            b = imgnd.A(":", ":", 2);

**Comment by goodtogood** [comment]
both of two work correctly.
thank you so much!
