### ISSUE TITLE
array.shape[]

### ISSUE THREAD

**Issue by yangjiandendi** [Quansight-Labs/numpy.net#14]
how  can i get the value from .shape?
like in numpy i have `a=[1,2,3]`, and i could get `x=a.shape[0]`.

**Comment by KevinBaselinesw** [comment]
The shape class has iDims array.  See the 2 unit tests below.

  def test_simpleShape_1(self):

        a=np.array([1,2,3])
        x=a.shape[0]

        print(x)

******************************


        [TestMethod]
        public void test_simpleShape_1()
        {
            var a = np.array(new int[] { 1, 2, 3 });
            var x = a.shape.iDims[0];
            print(x);

            return;
        }

**Comment by yangjiandendi** [comment]
> The shape class has iDims array. See the 2 unit tests below.
> 
> def test_simpleShape_1(self):
> 
> ```
>     a=np.array([1,2,3])
>     x=a.shape[0]
> 
>     print(x)
> ```
> 
> ```
>     [TestMethod]
>     public void test_simpleShape_1()
>     {
>         var a = np.array(new int[] { 1, 2, 3 });
>         var x = a.shape.iDims[0];
>         print(x);
> 
>         return;
>     }
> ```
