### ISSUE TITLE
String parsing returns 0

### ISSUE THREAD

**Issue by Happypig375** [Quansight-Labs/numpy.net#18]
```cs
using NumpyDotNet;
np.array(new[,]{
    {"0", "1"},
    {"1", "0"},
  }).astype(np.Float64)
```
Expected
```
DOUBLE 
{ { 0.0, 1.0 },
  { 1.0, 0.0 } }
```
Actual
```
DOUBLE 
{ { 0.0, 0.0 },
  { 0.0, 0.0 } }
```

**Comment by KevinBaselinesw** [comment]
I agree the behavior differs from python.  Currently I am not trying to convert any strings to numbers.
Is this a real world problem that you are hitting?   I can try to work on it if it is.

**Comment by Happypig375** [comment]
How do you define the "real world"? You can choose not to fix these differing behaviors, but definitely, other people who try to use NumpyDotNet like Numpy will fall into these traps.

**Comment by KevinBaselinesw** [comment]
Is there a private email I can send an updated DLL to you instead of generating a new release?   You can send me kevin at baselinesw.com

**Comment by Happypig375** [comment]
Are there difficulties in generating a new release? I'm using NumpyDotNet from .NET Interactive Notebooks where updating from NuGet is automatic.

**Comment by KevinBaselinesw** [comment]
It is a little bit more work to generate new release.  If you are going to continue testing and finding issues, I would rather send fixes to you directly until whatever you are doing is stable.   Then I will do a release with all the improvements.

FYI, I have the string conversion changes made.  

I investigated the np.delete issue and unfortunately I won't be able to fix that quickly.  I don't support deleting by axis which is what your sample does.  It is too much work.

**Comment by Happypig375** [comment]
> It is a little bit more work to generate new release.

Ah, sure then. I'll email
> I don't support deleting by axis which is what your sample does

Actually it does work, I can work around with a reshape afterwards.

**Comment by Happypig375** [comment]
fixed

**Comment by KevinBaselinesw** [comment]
>>Actually it does work, I can work around with a reshape afterwards.

Yes, that is correct.
