### ISSUE TITLE
[Suggest] make Ndarray == closer to numpy

### ISSUE THREAD

**Issue by ChengYen-Tang** [Quansight-Labs/numpy.net#38]
There is no Equals method for ndarray in numpy, so I think in numpy.net if you want to compare ndarray instence, you should use Equals instead of ==.

```
  ndarray a1 = new ndarray();
  ndarray a2 = new ndarray();

a. Compare elements in two ndarrays
  ndarray result = a1 == a2;

b. Compare instance of two objects
  bool result = a1.Equals(a2);

c. Check ndarray is null
  bool result = a1 is null;
  bool result = a1 is not null; //need C# 7.0 or later
  --Solution--
  1. set <LangVersion>latest</LangVersion> in csproj
      https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/configure-language-version#c-language-version-reference
  2. bool result = !(a1 is null);
```

If you accept my proposal, but you are not free, I can assist you.

**Comment by KevinBaselinesw** [comment]
== is a special .NET case.  If you override that, you also have to override != and that creates other problems in the code.

Try using np.equals() and np.array_equal() instead.

Also, I already overide ndarray.Equals()

**Comment by ChengYen-Tang** [comment]
What are the problems, can you explain?
I think override != is a must

<img width="488" alt="image" src="https://user-images.githubusercontent.com/32535494/188259391-954f7650-4cad-4e4d-bb4c-af6d29a2145f.png">
