### ISSUE TITLE
Get data for a shape using a range

### ISSUE THREAD

**Issue by ChengYen-Tang** [Quansight-Labs/numpy.net#42]
In python I can use `array.shape[1:]`
C# has similar functionality
https://learn.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-8#indices-and-ranges
alternative method: `array.shape.iDims[1..]`

**Comment by KevinBaselinesw** [comment]
I just pushed up a new release that supports selecting shape dimensions via Slice (new Slice(1,null, null) or slice string ("1:").

**Comment by ChengYen-Tang** [comment]
thank you
