### ISSUE TITLE
Convolve return ndarray with wrong size

### ISSUE THREAD

**Issue by DeanZhuo** [Quansight-Labs/numpy.net#60]
Version: 0.9.86.1

I have two ndarray object with different length, 27 and 35. When I called:
`var result = np.convolve(hlpf, hhpf, NumpyLib.NPY_CONVOLE_MODE.NPY_CONVOLVE_FULL);`
In the output window:
`array length: 27, 35, 53 `

Any idea what might have caused this?

**Comment by KevinBaselinesw** [comment]
You have discovered a bug.  I am working on a fix now.

**Comment by KevinBaselinesw** [comment]
Get the latest version 0.9.86.2 to solve this problem.  Thank you.
